name: Build WASM (tag release)

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build WASM
        run: wasm-pack build --release --target bundler --out-dir builds

      - name: Fix package metadata
        run: |
          cd builds
          npm pkg set name="@truekendor/wasm-chess"
          npm pkg set type="module"
